[project]
name = "site-governanca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.10"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-click>=0.9.0",
    "mkdocs-material>=9.6.18",
    "mkdocs-video>=1.5.0",
]
